### ISSUE TITLE
relative path in bin

### ISSUE THREAD

**Issue by jacekk** [Andarist/npm-self-link#1]
```js
const npmSelfLink = require('..')
```
What will require that line above, if it is present in `bin/npm-self-link.js`? IMHO nothing, bc there is no `index.js` file within the root of this project. If case I'm wrong, please give me a hint what kind of a magic happens in here.

**Comment by haltcase** [comment]
Sure, there's a bit of actual magic happening. Node's [`require` algorithm](https://nodejs.org/api/modules.html#modules_all_together) follows the `main` field in a `package.json` if no `index.js` is found, which [in this case](https://github.com/Andarist/npm-self-link/blob/3da9d03fb0a596c9e9f1b1feaf0d46c14d802e1c/package.json#L5) points to `./lib/index.js`.

**Comment by jacekk** [comment]
@citycide That explains a lot. Many thanks.
